{% set version = "0.18.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlr3misc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr3misc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr3misc/mlr3misc_{{ version }}.tar.gz
  sha256: 65a250521f77e9938067eac731f53d53e56372668d28941a3d4a84056e3110f5

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-backports >=0.1.5
    - r-checkmate
    - r-cli
    - r-data.table
    - r-digest
  run:
    - r-base
    - r-r6
    - r-backports >=0.1.5
    - r-checkmate
    - r-cli
    - r-data.table
    - r-digest

test:
  commands:
    - $R -e "library('mlr3misc')"           # [not win]
    - "\"%R%\" -e \"library('mlr3misc')\""  # [win]

about:
  home: https://mlr3misc.mlr-org.com, https://github.com/mlr-org/mlr3misc
  license: LGPL-3.0-only
  summary: Frequently used helper functions and assertions used in 'mlr3' and its companion packages. Comes with helper functions for functional programming, for printing, to work with 'data.table', as well as some generally useful 'R6' classes. This package also supersedes the package 'BBmisc'.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git

# Package: mlr3misc
# Title: Helper Functions for 'mlr3'
# Version: 0.7.0
# Authors@R: c(person(given = "Michel", family = "Lang", role = c("cre", "aut"), email = "michellang@gmail.com", comment = c(ORCID = "0000-0001-9754-0393")), person(given = "Patrick", family = "Schratz", role = "aut", email = "patrick.schratz@gmail.com", comment = c(ORCID = "0000-0003-0748-6624")))
# Description: Frequently used helper functions and assertions used in 'mlr3' and its companion packages. Comes with helper functions for functional programming, for printing, to work with 'data.table', as well as some generally useful 'R6' classes. This package also supersedes the package 'BBmisc'.
# License: LGPL-3
# URL: https://mlr3misc.mlr-org.com, https://github.com/mlr-org/mlr3misc
# BugReports: https://github.com/mlr-org/mlr3misc/issues
# Depends: R (>= 3.1.0)
# Imports: backports (>= 0.1.5), checkmate, data.table, R6
# Suggests: callr, evaluate, paradox, testthat (>= 3.0.0)
# Encoding: UTF-8
# NeedsCompilation: yes
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# RoxygenNote: 7.1.1
# Packaged: 2021-01-05 13:04:45 UTC; lang
# Author: Michel Lang [cre, aut] (<https://orcid.org/0000-0001-9754-0393>), Patrick Schratz [aut] (<https://orcid.org/0000-0003-0748-6624>)
# Maintainer: Michel Lang <michellang@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-01-05 20:00:24 UTC
